// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7dFEeE8M31j_VeP-v9Ju_z8XFOduRi1c',
    appId: '1:890349740264:web:3be239783913be5cb0695d',
    messagingSenderId: '890349740264',
    projectId: 'restaurant-reservation2-b02f0',
    authDomain: 'restaurant-reservation2-b02f0.firebaseapp.com',
    storageBucket: 'restaurant-reservation2-b02f0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqTW5Ix4JtLJZgOtFxS_Nx3wHMDN7cfdg',
    appId: '1:890349740264:android:9878c1cb9ce5cb0ab0695d',
    messagingSenderId: '890349740264',
    projectId: 'restaurant-reservation2-b02f0',
    storageBucket: 'restaurant-reservation2-b02f0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUYK2vuev0pQ6_2BGd1oxVN1iaICuJxAk',
    appId: '1:890349740264:ios:5bc810cad6fcbc84b0695d',
    messagingSenderId: '890349740264',
    projectId: 'restaurant-reservation2-b02f0',
    storageBucket: 'restaurant-reservation2-b02f0.firebasestorage.app',
    iosBundleId: 'com.restaurantapp.restaurantReservationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUYK2vuev0pQ6_2BGd1oxVN1iaICuJxAk',
    appId: '1:890349740264:ios:5bc810cad6fcbc84b0695d',
    messagingSenderId: '890349740264',
    projectId: 'restaurant-reservation2-b02f0',
    storageBucket: 'restaurant-reservation2-b02f0.firebasestorage.app',
    iosBundleId: 'com.restaurantapp.restaurantReservationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7dFEeE8M31j_VeP-v9Ju_z8XFOduRi1c',
    appId: '1:890349740264:web:83c88b4532bad87eb0695d',
    messagingSenderId: '890349740264',
    projectId: 'restaurant-reservation2-b02f0',
    authDomain: 'restaurant-reservation2-b02f0.firebaseapp.com',
    storageBucket: 'restaurant-reservation2-b02f0.firebasestorage.app',
  );

}